# Model Series Rules Configuration
# Order matters - first match wins
# Each provider section defines series in desired sort order

[openai]
series = [
  { name = "gpt-4o", pattern = "^gpt-4o$" },
  { name = "gpt-4o-mini", pattern = "^gpt-4o-mini" },
  { name = "o1", pattern = "^o1(?!-mini)" },
  { name = "o1-mini", pattern = "^o1-mini" },
  { name = "embedding", patterns = [
    "^text-embedding-3-(small|large)$",
    "^text-embedding-ada-002$",
  ] },
  { name = "realtime", pattern = "^gpt.*realtime.*$" },
  { name = "audio", pattern = "^whisper" },
  { name = "legacy", pattern = "^gpt-4-turbo" },
  { name = "legacy", pattern = "^gpt-4" },
  { name = "legacy", pattern = "^gpt-3" },
]

[anthropic]
series = [
  { name = "sonnet", pattern = "sonnet" },
  { name = "haiku", pattern = "haiku" },
  { name = "opus", pattern = "opus" },
  { name = "legacy", pattern = "claude-instant" },
  { name = "legacy", pattern = "claude-2" },
]
